pipeline {
    agent {
        label 'docker'
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('NPM Version') {
            agent {
                docker { 
                    image 'node:latest' 
                    reuseNode true
                }
            }
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }
        stage('Dependencies') {
            agent {
                docker { 
                    image 'node:latest' 
                    reuseNode true
                }
            }
            steps {
                sh 'sudo chown -R 1001:1001 "/.npm"'
                sh 'npm install'
            }
        }
        stage('Build') {
            agent {
                docker { 
                    image 'node:latest' 
                    reuseNode true
                }
            }
            steps {
                sh 'sudo chown -R 1001:1001 "/.npm"'
                sh 'npm run build'
            }
        }
    }
}
